# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Config-Find
version:      0.16
version_from: lib/Config/Find.pm
installdirs:  site
requires:
    File::HomeDir:                 0
    File::Spec:                    0
    File::Which:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
